Secretonyxia
InseeFrLab/onyxia-api pull request #424
Opened 2024-05-15 16:37 UTC by fcomte

2024-05-16 08:51 UTC, johnksv commented
Hi! Can you give a brief description of what this PR introduce? 😊

2024-05-16 10:57 UTC, fcomte commented
This PR modify how we manage metadata for specific onyxia information. Before this PR those metadata (owner, share, friendly name) was kept inside helm values. This PR manage those metadata inside onyxia specific secrets. Those secrets are deleted if thé release IS delete without onyxia because of the ownerReference referencing the helm release secrets

2024-05-16 10:59 UTC, fcomte commented
It will also enable the modification of friendly name ans the sharing status without update the release

2024-05-21 11:36 UTC, olevitt commented
This looks ok to me.  
@johnksv any remark on this PR ?

2024-05-21 11:37 UTC, olevitt approved these changes

2024-05-21 11:40 UTC, olevitt requested changes

2024-05-21 11:40 UTC, olevitt commented on onyxia-api/src/main/java/fr/insee/onyxia/api/services/impl/HelmAppsService.java
> +        Secret secret =
This logic should be moved in a separate method so that it can be reused and mutualized

2024-06-10 12:56 UTC, olevitt approved these changes

2024-06-10 13:18 UTC, merged