Implement refresh endpoint (as an admin endpoint)
InseeFrLab/onyxia-api pull request #522
Opened 2024-11-21 14:41 UTC by skykanin

2024-11-21 15:03 UTC, skykanin commented
don't merge this yet, I still want to explore implementing unit tests for this

2024-11-21 21:17 UTC, olevitt requested changes
Almost good to go, there is just an oversight in the default configuration

2024-11-21 21:17 UTC, olevitt commented on onyxia-api/src/main/resources/application.properties
> +admin.enabled=true
We have to set this to `false` by default :)

2024-11-22 07:39 UTC, olevitt approved these changes
LGTM, thank you ! :+1:

2024-11-22 07:40 UTC, merged